[package]
name = "hello-solana"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.14.14" # Compatible with CLI v2.x
solana-client = "1.11.0"
solana-sdk = "1.11.0"
tokio = { version = "1", features = ["full"] }

